// Generated by BUCKLESCRIPT VERSION 2.1.0, PLEASE EDIT WITH CARE
'use strict';

var GraphqlRequest = require("graphql-request");

var uri = "https://api.graph.cool/simple/v1/cj9o4se940gsu0148s5a4helr";

var query = "\n    query allCompanies($filter: String) {\n        companies: allCompanies(filter: \n        { name_contains: $filter\n        }) {\n          id\n          name\n        }\n      }";

GraphqlRequest.request(uri, query).then((function (data) {
        return Promise.resolve((console.log(data), /* () */0));
      }));

exports.uri   = uri;
exports.query = query;
/*  Not a pure module */
