// Generated by BUCKLESCRIPT VERSION 2.1.0, PLEASE EDIT WITH CARE
'use strict';

var GraphqlRequest = require("graphql-request");

var uri = "https://api.graph.cool/simple/v1/movies";

var query = (
    `{
        Movie(title: "Inception") {
            releaseDate
            actors {
            name
            }
        }
    }`
);

GraphqlRequest.request(uri, query).then((function (data) {
        return Promise.resolve((console.log(data), /* () */0));
      }));

exports.uri   = uri;
exports.query = query;
/* query Not a pure module */
