// Generated by BUCKLESCRIPT VERSION 2.1.0, PLEASE EDIT WITH CARE
'use strict';


var c1 = {
  high: 3
};

var c2 = {
  high: 3,
  low: 2
};

var high = c1.high;

var low = c1.low;

console.log(low);

console.log(high);

exports.c1   = c1;
exports.c2   = c2;
exports.high = high;
exports.low  = low;
/* high Not a pure module */
